Если асинхронное задание Task генерирует необработанное исключение - оно поглощается и сохраняется в коллекции, а потоек разрешается вернуться в пул. Затем при вызове метода Wait() или св-ва Result эти члены вбросят исключение `System.AggregateException`.
	Тип AggregateException иенкапсулирует коллекцию исключений (которые генерируются, если родительское задание порождает многочисленные дочерние задания. приводящие к исключениям)



**Если ни разу не вызывался метод Wait или Result и не обращались к св-ву Exception класса Task - код не узнает о появившихся исключениях.** Для распознавания скрытх исключений можно зарегистрировать метод обратного вызова со статическим событием `UnobservedTaskException` класса TaskScheduler. При унчтожении задания со скрытм исключением в ходе уборки мусора это событие активизируется потоком финализации уборщика мусора CLR. После этого обработчику события передается объект `UnobservedTaskExceptionEventArgs`, содержащий скрытое исключеение `AggregateException`.

